[package]
name = "nu_plugin_file"
version = "0.0.2"
authors = ["Darren Schroeder"]
edition = "2021"
repository = "https://github.com/fdncred/nu_plugin_file"
description = "a nushell plugin called file"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-plugin = "0.85.0"
nu-protocol = "0.85.0"

serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.105"
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = "0.25.2"
# tokio = { workspace = true, features = ["fs", "rt", "io-util"] }
# tokio = { version = "1.29", features = ["fs", "rt", "io-util"] }
# specta = { workspace = true }
specta = "1.0.5"
home = "0.5.5"
itertools = "0.11.0"

[dev-dependencies]
# tokio = { version = "1.29", features = ["fs", "rt", "macros"] }
